### ISSUE TITLE
Extension shows "ERROR" on site, but works correctly

### ISSUE THREAD

**Issue by mystiquewolf** [aunetx/smart-transparent-top-bar#3]
Settings also open and work. Everything works, apparently it's only the "ERROR" status.

**Comment by aunetx** [comment]
Thanks again, I did not know ^^
Was it the first time you installed the extension ? I will test it on a fresh installation

**Comment by mystiquewolf** [comment]
Yes, it is the first time. I love it!

**Comment by aunetx** [comment]
Thanks (so I know this is not a problem only when updating, what I was thinking before)

And thanks! I'm glad to see that my work is useful for other people (first time in all my open-source projects btw)
:)

**Comment by Senshi111** [comment]
same here but only after update

**Comment by aunetx** [comment]
Thanks to report it :)

**Comment by liubomirwm** [comment]
[journalctl-gnome-extensions.log](https://github.com/aunetx/smart-transparent-top-bar/files/4678408/journalctl-gnome-extensions.log)
Some errors in log here.. might be helpful.

**Comment by mystiquewolf** [comment]
https://drive.google.com/file/d/1XkhoIA--83YBJ748lcpiN4pfAnjBG3CW/view?usp=sharing
@aunetx Here, some logs that might be helpful. :)

**Comment by aunetx** [comment]
Thanks a lot @liubomirwm that's a lot of help! As I still can't reproduce this issue correctly, this will help me very much :)

**Comment by aunetx** [comment]
Okay I got it, thanks @liubomirwm !
It is nearly the same error as for #2 : to change the text colour, I need to iterate through children and change their own children's style value (yeah theming on gnome is hard)
But I hardcoded some values so that I can iterate quickly, and did not do runtime checks so when some extensions where installed, I ended up changing "style" value of some unknown elements (thus producing an error, and not changing text colours accordingly).

Sorry for this long explanation, I should be able to change this behaviour after my meal!

**Comment by aunetx** [comment]
Can anyone test the new version from git and tell me if it resolves the problem?
To install it:
```sh
git clone https://github.com/aunetx/smart-transparent-top-bar
cd smart-transparent-top-bar
make install
```
and then restart the shell :)

**Comment by mystiquewolf** [comment]
It now doesn't show the "ERROR" on GNOME extensions site, only shows the upgrade button.

**Comment by aunetx** [comment]
Ok thanks! That's normal (as I did not uploaded the extension yet), I will push it soon and it should be good in some days

**Comment by aunetx** [comment]
The extension has been reviewed, and the update seems to have removed the bug ^^
Please feel free to reopen the issue if it is not
